name: proctorix

services:
  devcontainer:
    container_name: ${COMPOSE_PROJECT_NAME}_devcontainer
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ../:/workspace:cached
    command: sleep infinity

  db:
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    image: postgres:16
    restart: always
    environment:
      # POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: postgres
      # POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DB: proctorix
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data   

  adminer:
    # container_name: ${COMPOSE_PROJECT_NAME}_adminer
    container_name: proctorix
    image: adminer:5.4.1
    # ports:
    #   - "${ADMINER_PORT}:8080"
    ports:
      - 8080

volumes:
  db_data: {} 